option(LIST_FEATURES "List available SIMD features and exit" OFF)

if(LIST_FEATURES)
    message(STATUS "")
    message(STATUS "=== Available Dynemit Features ===")
    message(STATUS "  - core              (CPU detection and SIMD level API)")
    message(STATUS "  - add               (SIMD-optimized element-wise vector addition)")
    message(STATUS "  - mul               (SIMD-optimized element-wise vector multiplication)")
    message(STATUS "  - sub               (SIMD-optimized element-wise vector subtraction)")
    message(STATUS "  - sum               (SIMD-optimized sum reductions for f64/u64/u32/u16)")
    message(STATUS "  - mean              (SIMD-optimized mean for f64/u64/u32/u16)")
    message(STATUS "  - min               (SIMD-optimized minimum reductions for f64/u64/u32/u16)")
    message(STATUS "  - max               (SIMD-optimized maximum reductions for f64/u64/u32/u16)")
    message(STATUS "  - variance          (SIMD-optimized sample variance for f64)")
    message(STATUS "  - skewness          (SIMD-optimized skewness for f64)")
    message(STATUS "  - kurtosis          (SIMD-optimized excess kurtosis for f64)")
    message(STATUS "  - entropy           (Shannon entropy for u16/u32/pre-counted frequencies)")
    message(STATUS "  - simpson           (Simpson's Diversity Index for u16/u32/pre-counted)")
    message(STATUS "  - hhi               (Herfindahl-Hirschman Index for u16/u32/pre-counted)")
    message(STATUS "  - gini              (Gini coefficient for f64/u64 sorted data)")
    message(STATUS "  - histogram         (range-based element counting for u16/u64)")
    message(STATUS "  - topk              (SIMD-optimized top-K concentration ratios)")
    message(STATUS "  - hill              (Hill estimator for heavy-tail detection)")
    message(STATUS "  - concentration     (composite concentration analysis)")
    message(STATUS "  - radixs            (SIMD-optimized LSD radix sort for u32/u64; counting sort for u16)")
    message(STATUS "===================================")
    message(STATUS "")
    message(STATUS "Usage modes:")
    message(STATUS "  1. All-in-one:    Link with -ldynemit (includes all features)")
    message(STATUS "  2. Modular:       Link with -ldynemit_core -ldynemit_<feature>")
    message(STATUS "  3. Core only:     Link with -ldynemit_core")
    message(STATUS "")
    message(FATAL_ERROR "Feature list displayed. Exiting as requested.")
endif()
